Percona-QA/package-testing

01proxy
insert_check.sh
playbooks/common_57.yml
plugins_test_57.sh
ps_version_check.sh
version_check.sh

Updated version_check to check if the correct server version is
installed
PS-5.7 playbook now automatically installs TokuDB plugin and runs the
tokudb compression check

Removed unnecessary and old files

---

molecule/pg-11/Jenkinsfile
molecule/pg-11/molecule/default/cleanup.yml
molecule/pg-11/molecule/default/molecule.yml
molecule/pg-11/molecule/default/prepare.yml
molecule/pg-11/molecule/default/side-effect.yml
molecule/pg-11/molecule/ec2/create.yml
molecule/pg-11/molecule/ec2/destroy.yml
molecule/pg-11/molecule/ec2/molecule.yml
molecule/pg-11/molecule/ec2/playbook.yml
molecule/pg-11/molecule/ec2/prepare.yml
molecule/pg-11/tasks/main.yml

default (vagrant) scenario still in place and can be run by the same command `molecule test`
new `ec2` scenario can be run with `molecule test -s ec2` command

Add ec2 scenario

---

molecule/JenkinsfilePS
molecule/playbooks/prepare.yml
molecule/ps-57-install/molecule/ec2/molecule.yml
molecule/ps-57-upgrade/molecule/ec2/molecule.yml
molecule/ps-80-install/molecule/ec2/molecule.yml
molecule/ps-80-maj-upgrade-to/molecule/ec2/molecule.yml
molecule/ps-80-upgrade/molecule/ec2/molecule.yml
tasks/test_prep.yml

Fix CentOS 6 root partition resize
Fix prepare playbook
Fix Debian lock file issue when starting prepare tasks

Run PS molecule tests in parallel for different distributions

---

bats/mysql-init-scripts.bats
bats/ps-admin_integration.bats
molecule/ps-57-install/molecule/default/cleanup.yml
molecule/ps-57-install/tasks/main.yml
molecule/ps-57-upgrade/tasks/main.yml
molecule/ps-80-install/molecule/default/cleanup.yml
molecule/ps-80-install/tasks/main.yml
molecule/ps-80-maj-upgrade-to/tasks/main.yml
molecule/ps-80-upgrade/tasks/main.yml
playbooks/common_56.yml
playbooks/common_57.yml
playbooks/ps_80.yml
playbooks/ps_80_major_upgrade_to.yml
playbooks/ps_80_upgrade.yml
scripts/ps_upgrade_partitioning.sh
tasks/test_prep.yml

Add ps_80_major_upgrade_to.yml
Created script for native partitioning upgrade 5.7 to 8.0
Disabled selinux on centos6 because different images have it in enforcing

Add ps_80_major_upgrade_to.yml

---

binary-tarball-tests/ps/run.sh
binary-tarball-tests/ps/test-ps-binary-tarball.groovy

Tests: https://ps80.cd.percona.com/job/test-ps-binary-tarball-illia/7/

ENG-946: Install & use python3.6 for Xenial builds

---

binary-tarball-tests/ps/test-ps-binary-tarball.groovy
binary-tarball-tests/pxc/cleanup.sh
binary-tarball-tests/pxc/conf/node1.cnf
binary-tarball-tests/pxc/conf/node2.cnf
binary-tarball-tests/pxc/conf/node3.cnf
binary-tarball-tests/pxc/mysql.py
binary-tarball-tests/pxc/run.sh
binary-tarball-tests/pxc/settings.py
binary-tarball-tests/pxc/test-pxc-binary-tarball.groovy
binary-tarball-tests/pxc/test-pxc-binary-tarball.yml
binary-tarball-tests/pxc/tests/test_pxc_dynamic.py
binary-tarball-tests/pxc/tests/test_pxc_static.py

https://pxc.cd.percona.com/job/test-pxc-binary-tarball/16/

PXC-3447: Added PXC binary tarball package testing job

---

playbooks/pmm2-client_integration.yml

tested here https://pmm.cd.percona.com/blue/organizations/jenkins/package-testing/detail/package-testing/242/pipeline

PMM-8277 client integration tests

---

docker-image-tests/ps/Jenkinsfile
docker-image-tests/ps/settings.py
docker-image-tests/ps/tests/test_ps_static.py

Two things are fixed in this PR :
1) Yum and Microdnf configured against specific PS version
2) TokuDB removed from PS 8.0 while it will work with PS 5.7.

Fixing Docker job 

---

docker-image-tests/ps/Jenkinsfile
docker-image-tests/ps/tests/test_ps_static.py

Remove microdnf as it is not working PS 5.7 also

Fixing Docker job

---

bats/ps-admin_unit.bats

Updated tests w.r.t to PS version

Update w.r.t removal of tokudb package

---

tasks/install_and_run_pxc80.yml
templates/my_rpm_80.j2

Resolve ansible_eth0 issue for pxc80

add ansible_default_ipv4 for resolving eth0 issue for pxc80

---

tasks/install_sysbench.yml

Remove the sysbench exception for Debian 11 Bullseye.

PS-8342 Add Debian 11 support for package testing.

---

docker-image-tests/ps/Jenkinsfile
docker-image-tests/ps/settings.py
docker-image-tests/ps/tests/test_ps_dynamic.py

Skip component installation in PS 5.7

Docker job update w.r.t PS 5.7

---

molecule/pdmysql/pdps_setup/molecule/debian-11/molecule.yml
molecule/pdmysql/pdps_setup/tasks/main.yml
molecule/pdmysql/pdpxc_setup/tasks/main.yml

PDPS|PDPXC: non-interactive mode for percona-release setup and deb11 update

---

tasks/install_sysbench.yml

Commented out sysbench-tpcc for time-being

Removed sysbench-tpcc 

---

playbooks/ps_80.yml

Add warnings check for ps 80  using the env check_warnings

PS 8347 add check for warnings ps 80 test

---

playbooks/ps_80.yml

Add debug task for fetching version-check.log file output

PS-8347 Add the debug task for fetching the output of the log file.

---

playbooks/ps_80_major_upgrade_to.yml
playbooks/ps_80_upgrade.yml

Add conditions for ps80 upgrade playbooks to use install_mysql_shell env variables as used in ps_80.yml

PS-8363 add install_mysql_shell optional condition for upgrade playbooks ps80

---

playbooks/ps_80.yml
playbooks/ps_80_major_upgrade_to.yml
playbooks/ps_80_upgrade.yml
plugins_test_80.sh

Disable Percona Toolkit installation till its supported in OL9 and Jammy
Plugins update to test authentication_ldap_sasl and authentication_fido

Disable Percona Toolkit installation till its supported in OL9 and Jammy

---

playbooks/ps_80.yml
tasks/install_sysbench.yml

Disable sysbench installation till its supported in OL9 

---

playbooks/ps_80.yml

Disabling package test as percona-server-shared-compat is not available in OL9

---

bats/ps-admin_helper.bash
package_check.sh
playbooks/ps_80.yml
scripts/mysql-comp-test/mysql_comp_test.sh
scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh
tasks/install_sysbench.yml
tasks/test_prep.yml

* Updated package_check.sh script as OL9 does'nt have percona-server-shared-compat
* updated scripts to replace service with systemctl as OL9 does'nt support service command

Changes w.r.t OL9 distribution

---

binary-tarball-tests/ps/settings.py
binary-tarball-tests/ps/test-ps-binary-tarball-56.groovy

Tarball Test Job that supports Bionic , Buster and Centos 7 for PS -5.6

Update w.r.t PS-5.6 tarball

---

binary-tarball-tests/pxc/test-pxc-binary-tarball.groovy

Working test: https://pxc.cd.percona.com/job/test-pxc-binary-tarball/

Add OL9 and Jammy to pxc tarball tests

---

playbooks/proxysql.yml
playbooks/proxysql2.yml
playbooks/proxysql2_upgrade.yml
playbooks/proxysql_upgrade.yml
version_check.sh

Successful job run with changes:  https://pxc.cd.percona.com/job/proxysql-package-testing-all/35/

Proxysql: check all binaries in packages

---

router-docker_test.sh

This script does the following :
* Configure 3 node Innodb cluster 
* Configure percona-mysql-router through docker image.
* Run some basic tests like Data insertion through sysbench , Replication and fault tolerance .

Configure InnoDB CLuster and  percona-mysql-router through docker image on local

---

molecule/pdmysql/pdpxc/molecule/centos-7/molecule.yml
molecule/pdmysql/pdpxc/molecule/debian-10/molecule.yml
molecule/pdmysql/pdpxc/molecule/debian-11/molecule.yml
molecule/pdmysql/pdpxc/molecule/oracle-8/molecule.yml
molecule/pdmysql/pdpxc/molecule/oracle-9/molecule.yml
molecule/pdmysql/pdpxc/molecule/ubuntu-bionic/molecule.yml
molecule/pdmysql/pdpxc/molecule/ubuntu-focal/molecule.yml
molecule/pdmysql/pdpxc/molecule/ubuntu-jammy/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/centos-7/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/debian-10/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/debian-11/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/oracle-8/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/oracle-9/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/ubuntu-bionic/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/ubuntu-focal/molecule.yml
molecule/pdmysql/pdpxc_setup/molecule/ubuntu-jammy/molecule.yml

…setup used by pdpxc and pdpxc-parallel jenkins job

Add job-name under instance_tag for aws molecule for pdpxc and pdpxc_setup used by pdpxc and pdpxc-parallel jenkins job

---

scripts/check-ec2-instances.sh

Script to check ec2 instances that have been up since past 2 days
Used by ec2-instance-checks jenkins job

Create check-ec2-instances.sh script

---

playbooks/ps_80_kmip.yml

Updated tests for Bookworm and Amazon Linux 2 
Added test to check if PyKMIP server is up and running

Update KMIP tests For Debian Bookworm and Amazon linux 2

---

binary-tarball-tests/pxc/test-pxc-binary-tarball.groovy

Fix naming convention for PXC tarball

---

.github/workflows/pmm-package-test-runner.yml
playbooks/pmm2-client_integration_custom_path.yml

Tis fix required for new FB action to switch version between tarball and number

PMM-9527 fixed runner to test new job

---

.github/workflows/pmm-package-test-matrix-full.yml
.github/workflows/pmm-package-test-matrix.yml
.github/workflows/pmm-package-test-single.yml

Updated matrix jobs grouping:
* **matrix:** https://github.com/Percona-QA/package-testing/actions/runs/7649317746
* **full matrix:** https://github.com/Percona-QA/package-testing/actions/runs/7649290626

PMM-7 matix view update

---

.github/workflows/pmm-package-test-fb.yml
.github/workflows/pmm-package-test-runner.yml
tasks/verify_pmm_server_version.yml
tasks/verify_pmm_status_versions.yml

Fixed pmm-server version check for "release candidate" case

PMM-7 fixed server check for RC

---

.github/workflows/pmm-package-test-fb.yml
.github/workflows/pmm-package-test-matrix-full.yml
.github/workflows/pmm-package-test-runner.yml
playbooks/pmm2-client_custom_path.yml
playbooks/pmm2-client_integration_custom_port.yml
playbooks/pmm2-client_integration_upgrade.yml
playbooks/pmm2-client_integration_upgrade_custom_path.yml
playbooks/pmm2-client_integration_upgrade_custom_port.yml
tasks/verifications_set_for_pmm_client.yml
tasks/verifications_set_for_pmm_client_after_upgrade.yml
tasks/verify_exporter_port_output.yml

* fixed _pmm2-client_integration_upgrade_custom_port_ test
* fixed _pmm2-client_custom_path_ test
* added optimizations and fixes for FB jobs
* updated displayed tests names for full matrix

PMM-11046 pmm2-client_integration_upgrade_custom_port updated

---

tasks/install_ps57.yml

https://github.com/percona/pmm-qa/actions/runs/10006597402

PMM-13234: Fix centos-7

---

playbooks/pmm2-client_integration.yml
playbooks/pmm2-client_integration_auth_config.yml
playbooks/pmm2-client_integration_custom_path.yml
playbooks/pmm2-client_integration_custom_port.yml
playbooks/pmm2-client_integration_upgrade.yml
playbooks/pmm2-client_integration_upgrade_custom_path.yml
playbooks/pmm2-client_integration_upgrade_custom_port.yml
tasks/verifications_set_for_pmm_client_after_upgrade.yml
tasks/verify_pmm2_metric.yml

https://github.com/percona/pmm-qa/actions/runs/10701912703/job/29672616458

PMM-7: Metric mongodbup fix

---

playbooks/pxb_80.yml
playbooks/pxb_80_kmip.yml
playbooks/pxb_80_kms.yml
playbooks/pxb_80_tarball.yml
playbooks/pxb_80_upgrade.yml
playbooks/pxb_80_upstream.yml
tasks/enable_pxb_80_main_repo.yml
tasks/enable_pxb_80_testing_repo.yml
tasks/test_prep.yml

pxb-pt 80 fix ligbflags

---

playbooks/pmm2-client_integration.yml
tasks/install_and_add_to_pmm_pdpgsql_16.yml
tasks/pmm2-client_test_enabled_db_arm.yml

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-package-testing-arm/detail/pmm2-package-testing-arm/3239/pipeline/

PMM-13353: Package Testing for PMM Arm client

---

playbooks/pmm3-client_integration.yml
tasks/install_and_add_to_pmm_pdpgsql_16.yml
tasks/pmm3-client_test_enabled_db.yml
tasks/pmm3-client_test_enabled_db_arm.yml
tasks/pmm3_client_test_prepare.yml
tasks/verify_pmm3_metric.yml

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-package-testing-arm/detail/pmm3-package-testing-arm/66/pipeline/

PMM-13264: Package Testing for PMM Arm client v3 (#760)

---

playbooks/pmm3-client_integration.yml
playbooks/pmm3-client_integration_custom_path.yml
playbooks/pmm3-client_integration_custom_port.yml
tasks/install_and_add_to_pmm_pdpgsql_16.yml
tasks/verifications_set_for_pmm3_client.yml
tasks/verify_pmm2_metric.yml
tasks/verify_pmm3_client_config.yml
tasks/verify_pmm3_metric.yml

https://github.com/percona/pmm-qa/actions/runs/11834808223

PMM-7 Package testing fixes for v3 beta
