package_check.sh

name is different than for 5.6 and 5.7 (it has additional "rel" similar
to CentOS packages).

Script was failing when checking PS-5.5 on Debian/Ubuntu because version

---

molecule/playbooks/create.yml

This fixes ssh key usage for ec2 instances with molecule.
Also it increases ec2 instance volume size from 8Gb to 16Gb because some of the tests were running out of disk space.
Creation of molecule instances in jenkins pipeline can be used like this:
```
withCredentials([sshUserPrivateKey(credentialsId: 'MOLECULE_AWS_PRIVATE_KEY', keyFileVariable: 'MOLECULE_AWS_PRIVATE_KEY', passphraseVariable: '', usernameVariable: ''), [$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AMI/OVF', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
sh '''
...
'''
}
```

Fix creating ec2 instances for molecule

---

molecule/JenkinsfilePS

This fixes the issues with molecule installation in the `test-ps-pkg` job. It does not fix the job itself, though; molecule now runs, but it seems to fail due to other reasons. Compare outputs of builds [#160](https://ps80.cd.percona.com/view/QA/job/test-ps-pkg/160) and [#171](https://ps80.cd.percona.com/view/QA/job/test-ps-pkg/171).

Fix molecule install

---

playbooks/common_57.yml
playbooks/common_57_major_upgrade_from.yml
playbooks/common_57_major_upgrade_to.yml
playbooks/common_57_upgrade.yml
playbooks/ps_80.yml
playbooks/ps_80_major_upgrade_to.yml
playbooks/ps_80_upgrade.yml
scripts/ps_keyring_plugins_test/keyring_vault_test.j2

This PR changes the `ps_80*.yml` and `common_57*.yml` playbooks so that they use the existing `setup_local_vault.yml` tasks from the molecule jobs to launch a local instance of Vault.
This is in opposition to the previous behaviour of connecting to a pre-existing Vault server, which is accessible from the old Jenkins instance's internal network, but isn't accessible from the new Jenkins instances. The purpose of this change is to make it possible to run these playbooks on the new Jenkins, but it should work just fine on the existing jobs that run them in the old Jenkins.
Since the playbook now launches its own Vault, without depending on Jenkins-provided credentials for the certificates or internal network access, there is no need to skip keyring-related steps when running it locally, so …

Setup keyring vault locally in PS playbooks

---

binary-tarball-tests/ps/mysql.py
binary-tarball-tests/pxc/Vagrantfile
binary-tarball-tests/pxc/mysql.py
binary-tarball-tests/pxc/run.sh
binary-tarball-tests/pxc/settings.py
binary-tarball-tests/pxc/tests/test_pxc_dynamic.py
binary-tarball-tests/pxc/tests/test_pxc_static.py

This PR fixes the binary tarball tests for PXC 5.7 and adds a few quality-of-life improvements. Tested locally with Centos 8 and Debian Stretch. Main changes are as follows:
- Updated list of expected files and symlinks for testing version 5.7.
- Fixed cluster SST connection in version 5.7.
- Added installation of XtraBackup 2.4 to the run script when testing version 5.7.
- Removed some unused functions or unneeded features from the PXC binary tarball tests, such as a sleep statement after shutdown or logs cleanup.
- Implemented automatic shell escaping and quoting to SQL query runs, in both PXC and PS binary tarball tests.
- Added new test on cluster size.
- Changed existing tests on plugin/function installation so that the installation is asserted against non-primary nodes.
- Added more …

Fix PXC 5.7 binary tarball tests

---

binary-tarball-tests/pxc/run.sh
binary-tarball-tests/pxc/settings.py
binary-tarball-tests/pxc/tests/test_pxc_static.py

This PR calls `ldd` on the binaries under test for the PXC tarball, failing the test if any of the libraries it depends on is not found.
To do so, the listed binaries in `settings.py` are split into _executables_ (all files under test in `bin/`, which are expected to have `+x` set) and _binaries_ (the subset of the executables which is _actually_ a binary, as opposed to a perl script or a shell script or whatever), the latter being the ones you can run `ldd` on for the purposes of this test.
Also, `libev` is now installed unconditionally, as it is a linked library of the `xbcloud` binary in both PXB 2.4 and PXB 8.0.

Test linked libraries on PXC tarball binaries

---

binary-tarball-tests/ps/Vagrantfile
binary-tarball-tests/ps/settings.py
binary-tarball-tests/ps/test-ps-binary-tarball.groovy
binary-tarball-tests/ps/tests/test_ps_static.py

Porting some of the changes made to the PXC binary tarball tests in #79 and #81 over to the PS tests, specifically:
- Added a Vagrantfile with the contents of the Jenkins job to make local testing easier
- Implemented the linked libraries test as in PXC (see #81)
- Added a check to the symlink test to ensure the symlink destination exists

Test linked libraries in PS binary tarball

---

docker-image-tests/pxc/Jenkinsfile
docker-image-tests/pxc/settings.py
docker-image-tests/pxc/tests/test_pxc_cluster.py
docker-image-tests/pxc/tests/test_pxc_static.py

This PR fixes the docker image tests for PXC 5.7 by doing the following:
- Correcting the package versions and binaries that are checked for under 5.7
- Fixing how the cluster is initialised for 5.7
- Changing the expected version number to match the one in 5.7 CentOS packages

Fix PXC 5.7 Docker image tests

---

molecule/ps-innodb-cluster-router/tasks/main.yml

This fixes the PS InnoDB Cluster tests when using recent versions of mysql-shell, which expect `--options-password` or `--instance-password` to be used with `add-instance`, instead of `--password`.

Disambiguate "--password" option with "--options-password"

---

playbooks/pxc80_bootstrap.yml
playbooks/pxc80_common.yml
playbooks/pxc80_upgrade.yml

This PR hardcodes the PXC package-testing tests to always use `main` on the bootstrap playbook and `testing` for the common/upgrade playbooks, disregarding the `install_repo` environment variable.
This fixes an issue where the upgrade playbook would not actually test the upgrade, since `install_repo` always has the same value for a given Jenkins build, meaning it would attempt to upgrade from `main` to `main` or from `testing` to `testing`, which is a no-op.

Use `main` repo for PXC bootstrap and `testing` for common/upgrade

---

playbooks/pxc56_bootstrap.yml
playbooks/pxc56_common.yml
playbooks/pxc56_upgrade.yml
playbooks/pxc57_bootstrap.yml
playbooks/pxc57_common.yml
playbooks/pxc57_upgrade.yml
playbooks/pxc80_bootstrap.yml
playbooks/pxc80_common.yml
playbooks/pxc80_upgrade.yml

This PR is part of PXC-3742. It allows for splitting the PXC "install" and "upgrade" test runs, allowing for testing installation of the PXC version from any repo, as well as upgrade to the PXC version from any repo. It reverts the temporary fix in #92 and extends the functionality that existed before that PR to cover the experimental repo and PXC 5.7/5.6.
The main change in this PR is the addition of the `upgrade_repo` environment variable, separate from the existing `install_repo` environment variable, so that different repos can be used for install and upgrade.
On the Jenkins side, the matrix has been extended to parameterise over the "install" and "upgrade" test types. On the install test, the `install_repo` environment variable is set to the value of the corresponding build …

PXC-3742: Split "install" and "upgrade" playbooks for PXC

---

tasks/remove_ps56.yml
tasks/remove_ps80.yml
tasks/remove_pt.yml
tasks/remove_pxb24.yml
tasks/remove_pxb80.yml

There is a "misprint" in tasks/remove_*.yml tasks - the install is used in descriptions/names of tasks instead of remove which can mislead.

ENG-1056: change install word to remove in description/names of remove_*.yml tasks

---

tasks/enable_pxc57_experimental_repo.yml
tasks/enable_pxc57_main_repo.yml
tasks/enable_pxc57_testing_repo.yml

At the moment pxc-57 packages are located in 2 repos:
- pxc-57
- original.
Package testing Jenkins job https://jenkins.percona.com/view/RT/job/package-testing-pxc/ used pxc-57 and pxb-24 repos for tests. The new parameter will be added to Jenkins job: pxc57_repo (exported as $pxc57repo).
Depending on its value the following repos will be enabled:
- if pxc57_repo = pxc57 or is empty: pxc-57 and pxb-24 repos;
- if pxc57_repo = original: original repo.
Some notes:
- as qpress packages are not present in original testing yum repo, original release repo is also enabled for tests in  enable_pxc57_testing_repo.yml ( see https://jira.percona.com/browse/PXC-3813 );
The link to task with tests: https://jenkins.percona.com/view/RT/job/eleonora-package-testing-pxc/

PXC-3828 implement selection of original/pxc-57 repo for pxc57 package testing

---

playbooks/pxb_24_upstream.yml
playbooks/pxb_80_upstream.yml

The upstream keys have changed in 2022. The repo package and yum gpg key links were updated.

Update upstream repo package and gpg key for PXB package tests.

---

Vagrantfile.template.normal
tasks/test_prep.yml

Based on https://www.centos.org/centos-linux-eol/#:~:text=CentOS%20Linux%208%20will%20reach%20End%20Of%20Life%20(EOL)%20on,Stream%208%20in%20this%20case CenOS8 mirrors are not available any more. That is why CentOS8 package testing will fail. To fix it the mirrors should be replaced with vault.centos.org .

Use vault.centos.org archive instead of mirrors for CentOS8

---

binary-tarball-tests/ps/test-ps-binary-tarball.groovy

Remove Xenial and Centos6 distribution from Binary Tarball Test Job as it is EOL now.

Remove Xenial and Centos6 distribution from Binary Tarball Test Job

---

binary-tarball-tests/ps/test-ps-binary-tarball.groovy

As GLIBC version 2.12 is not needed after Centos6 EOL , so removing the code for checking glibc version and hardcoded it to 2.12

Fixed GLIBC Version in tarball job

---

docker-image-tests/pxc/settings.py

The Docker image test for pxc80 checks presence of the binaries (https://pxc.cd.percona.com/view/QA%208.0/job/qa-docker-image/). The list of binaries is in docker-image-tests/pxc/settings.py file (pxc80_binaries list). The list did not include all the binaries that are present in docker image for pxc80, that is why it was extended to include missing binaries.
Test run with the updated list of binaries: https://pxc.cd.percona.com/view/QA%208.0/job/qa-docker-image/123 .

Expand pxc80 binaries list for docker test

---

package_check.sh
playbooks/common_57_major_upgrade_from.yml

At the moment major PS57 major update from update fails because PS80 does not support TokuDB any more. To overcome this issue the TokuDB installation was removed from common_57_major_upgrade_from.yml. In addition I have removed bat tests and compression ones for PS57 as they are also run in common_57.yml . 
I have adjusted package_check.sh script to skip TokuDB check if $ps57_tokudb = "no" and added it to common_57_major_upgrade_from.yml test only.

Remove TokuDB and non-required tests

---

docker-image-tests/pxc/tests/test_pxc_cluster.py

The test to check whether garbd can connect to pxc5.7/pxc8.0 cluster was added. The check is performed based on the number of nodes in the wsrep_cluster_size. The first check is performed on the the garbd connect and the second one is performed in 6 minutes. 
The test is performed:
1. Oracle Linux 8 image is downloaded;
2. garbd from repo is installed in ol8 container.
3. The number of nodes is checked.

Add garbd check to pxc docker image test

---

binary-tarball-tests/ps/mysql.py
binary-tarball-tests/ps/test-ps-binary-tarball.groovy

`ERROR: ld.so: object '/mnt/jenkins/workspace/test-ps-binary-tarball/package-testing/binary-tarball-tests/ps/Percona-Server-8.0.28-20-Linux.x86_64.glibc2.17/lib/libHotBackup.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

PS-8281: libHotBackup.so error while running tarball job

---

molecule/pdmysql/pdps/molecule/tests/test_orchestrator.py
molecule/pdmysql/pdps/tasks/main.yml

In scope of https://jira.percona.com/browse/DISTMYSQL-198 the rpm packages were updated as follows:
- instead of 1 package (percona-orchestrator) now 3 packages are installed : 
* percona-orchestrator
* percona-orchestrator-cli
* percona-orchestrator-client
Now the 'percona-orchestrator-client' on rpm packages is no located in `/usr/bin/orchestrator-client` instead of `/usr/local/orchestrator/resources/bin/orchestrator-client` (the same as in upstream)

Use 3 rpm packages for orchestrator tests in pdps

---

molecule/pdmysql/pdps-minor-upgrade/molecule/tests/test_orchestrator.py
molecule/pdmysql/pdps-minor-upgrade/tasks/main.yml

In scope of https://jira.percona.com/browse/DISTMYSQL-198 the percona-orchestrator rpm packages were updated as follows:
instead of 1 package (percona-orchestrator) now 3 packages are installed :
percona-orchestrator
percona-orchestrator-cli
percona-orchestrator-client
Now the 'percona-orchestrator-client' on rpm packages is now located in /usr/bin/orchestrator-client instead of /usr/local/orchestrator/resources/bin/orchestrator-client (the same as in upstream).
In addition mysql-router and  mysql-shell upgrade test failed without `state: latest`.

Fix rpm orchestrator pkgs, mysql-router and  mysql-shell version in pdps minor upgrade

---

binary-tarball-tests/ps/test-ps-binary-tarball.groovy

Remove Debian Stretch from Binary Tarball Job as it is no longer supported

Remove Debian Stretch from Binary Tarball Job

---

client_check.sh
playbooks/client_test.yml
playbooks/ps_80.yml
scripts/log-warning-check.sh
version_check.sh

1) mysql shell installation option and backwards compatibility for version-check.sh script.
2) mysql shell installation option and backwards compatibility for client_check.sh script.
3) Modify the log_warning_check.sh for simple check output.
4) Modify the ansible playbook ps_80.yml to add var and env for mysql shell installation, 
5) Modify the ansible playbook ps_80.yml to add block and rescue for displaying output and stop the plays on warnings check failure.
5) Modify the ansible playbook client_test.yml to add var and env for mysql shell installation

PS 8347 client check and ps 80 ansible playbook and script modifications

---

client_check.sh
playbooks/client_test.yml
playbooks/ps_80.yml

1) Add install_mysql_shell conditional for Debian in client_check.sh for ps80
2) Add install_mysql_shell trigger for checking the version of mysql shell for ps80
3) Add structure similar to ps_80.yml for client_test.yml for conditional stdout/stderr display on the jenkins console during warnings detection.
4) Modify the "**install PS/PXC client and run the check**" task block in client_test.yml for classic and portable stdout/stderr forwarding. (Fixes stdout and sterr forwarding issues using ansible to client-check.log file in Debian)
5) Modify the "**Run the version_check.sh script**" task block in ps_80.yml for classic and portable stdout/stderr forwarding. (Fixes stdout and sterr forwarding issues using ansible to version-check.log file in Debian)

PS 8347 client check and ps_80.yml modifications 

---

plugins_test_56.sh
plugins_test_57.sh
plugins_test_57u.sh
plugins_test_80.sh

If the ERROR_LOG variable was empty - the script failed on : `ERROR_LOG=$(mysql -N -s -e "show variables like 'log_error';" | grep -v "Warning:" | grep -o "\/.*$")` execution and no error was output. To fix this `|| true` part and corresponding checks were added.

Add error about empty ERROR_LOG variable in plugins_test scripts

---

playbooks/ps_80.yml
playbooks/ps_80_major_upgrade_to.yml
playbooks/ps_80_upgrade.yml

Added a default value for install_mysql_shell ansible var.
In case variable value is yes or if the variable value is not defined we set it to ' ' by default and then use it via when condition in ps_80.yml
Tested for the following cases :-
install_mysql_shell is not defined/set caused installation of mysql shell.
install_mysql_shell="yes" caused installation of mysql shell.
install_mysql_shell="no" did not installed mysql shell and skipped the tasks.

PS-8392 Adding backwards compatibility for install_mysql_shell variable for ps80

---

molecule/pdmysql/pdps-minor-upgrade/molecule/tests/test_ps.py
molecule/pdmysql/pdps/molecule/tests/test_ps.py
molecule/pdmysql/pdps_setup/molecule/tests/test_ps.py

Two plugins are added in PS 8.0.30 , so we need to add their support in PDPS jobs also .
* authentication_ldap_sasl
* authentication_fido

Update plugin in PDPS Jobs

---

molecule/pdmysql/pdps-minor-upgrade/tasks/main.yml
molecule/pdmysql/pdps/tasks/main.yml
molecule/pdmysql/pdps_setup/tasks/main.yml

service module and systemd module are not working with oracle linux 9 distribution . So updating command module instead of service/systemd .

Update service module to command module to check proxysql status 

---

molecule/pxc/pxc57-bootstrap-upgrade/tasks/main.yml

Added the check pxc cluster in bootstrap molecule instead of common for pxc57 upgrade.

Remove the cluster check from bootstrap molecule for pxc57

---

bats/pxc-init-scripts.bats

Resolves the bats test restart using service command issue.

PXC 80 bats test issue, Increase sleep to 20s from 10s

---

playbooks/ps_80_kmip.yml

KMPI tests were failing for RHEL distros. For tests the client certificate was located in custom folder:
package-testing/kmip/client_certificate_john_smith.pem. On RHEL machines where the selinux was set to 'enforcing', the access to cert was blocked by SElinux, server did not get key for de-encryption and failed to start.

PS8.0.32: disable SElinux for kmip tests

---

molecule/pxc/pxc80-bootstrap-install/molecule/ubuntu-focal/molecule.yml
molecule/pxc/pxc80-bootstrap-upgrade/molecule/ubuntu-focal/molecule.yml
molecule/pxc/pxc80-common-install/molecule/ubuntu-focal/molecule.yml
molecule/pxc/pxc80-common-upgrade/molecule/ubuntu-focal/molecule.yml

AMI:        ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230207
AMI_ID:  ami-00712dae9a53f8c15

Add the updated ubuntu-focal AMI FEB2023 for PXC80 Molecule

---

docker-image-tests/orchestrator/requirements.txt
docker-image-tests/orchestrator/tests/test_orch_with_server.py

Extension for orchestrator docker tests. Test:
- sets up 2 PS servers in Docker with replication;
- sets up orchestrator 
- discovers source PS node, checks replication status after discover, after some load, after repl is stopped on server.
Successful test run: https://ps80.cd.percona.com/view/PDPS/job/orchestrator_docker/33/console

DISTMYSQL-278:Orchestrator_docker-setup PS repl and add it to orch

---

molecule/pdmysql/orchestrator/molecule/ubuntu-bionic/molecule.yml

Addition of job-name under instance-tags in aws molecule for PDPS Orchestrator test job

Add job-name under instance-tags in aws molecule for PDPS Orchestrator

---

molecule/ps-innodb-cluster/server/molecule/centos-7/molecule.yml
molecule/ps-innodb-cluster/server/molecule/debian-10/molecule.yml
molecule/ps-innodb-cluster/server/molecule/debian-11/molecule.yml
molecule/ps-innodb-cluster/server/molecule/debian-9/molecule.yml
molecule/ps-innodb-cluster/server/molecule/oracle-8/molecule.yml
molecule/ps-innodb-cluster/server/molecule/oracle-9/molecule.yml
molecule/ps-innodb-cluster/server/molecule/ubuntu-bionic/molecule.yml
molecule/ps-innodb-cluster/server/molecule/ubuntu-focal/molecule.yml
molecule/ps-innodb-cluster/server/molecule/ubuntu-jammy/molecule.yml

Add Molecule instance-tags for ps innodb testing job identification on aws console.

Add job-name under instance-tags in aws molecule for PS Innodb Testing

---

tasks/install_sysbench.yml

As sysbench-tpcc is not available for debian bookworm.

add exception for bookworm

---

tasks/verify_pmm2_metric.yml

Increased default waiting for metrics timeout to make tests more stable.

PMM-7 increased default wait

---

.github/workflows/pmm-package-test-fb.yml
.github/workflows/pmm-package-test-matrix-full.yml
Vagrantfile.template.pmm2-deb
Vagrantfile.template.pmm2-rpm
Vagrantfile.template.pmm2-ub

test results:  https://github.com/Percona-Lab/pmm-submodules/actions/runs/7834431133/job/21377989293

PMM-7 minor doc, jobs order and job name refactoring

---

molecule/pxb-binary-tarball/molecule/debian-11/molecule.yml

https://wiki.debian.org/Cloud/AmazonEC2Image/Bullseye

pxb tarball debian-11 fix: ami-02dda1c84e46dbe0a
